apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello
  namespace: flask-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-hello
  template:
    metadata:
      labels:
        app: flask-hello
    spec:  # ← QUI!
      imagePullSecrets:  # ← SPOSTATO QUI!
      - name: harbor-pull-secret
      containers:
      - name: flask
        image: test.local:30405/library/flask-hello:latest
        ports:
        - containerPort: 8081
        env:
        - name: FLASK_ENV
          value: "production"